package com.example.heroesapp.models

import android.os.Parcel
import android.os.Parcelable

data class CharacterItem(val id: Int, val name: String, val imagen: String, val descripcion: String) : Parcelable {
    // Constructor que toma un Parcel
    constructor(parcel: Parcel) : this(
        parcel.readInt(),
        parcel.readString() ?: "",
        parcel.readString() ?: "",
        parcel.readString() ?:""
    )

    // Método para escribir en el Parcel
    override fun writeToParcel(parcel: Parcel, flags: Int) {
        parcel.writeInt(id)
        parcel.writeString(name)
        parcel.writeString(imagen)
        parcel.writeString(descripcion)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object CREATOR : Parcelable.Creator<CharacterItem> {
        override fun createFromParcel(parcel: Parcel): CharacterItem {
            return CharacterItem(parcel)
        }

        override fun newArray(size: Int): Array<CharacterItem?> {
            return arrayOfNulls(size)
        }

        // Lista de personajes
        val characters = mutableListOf<CharacterItem>(
            CharacterItem(1, "Spiderman", "https://i.imgur.com/bHGENih.jpeg","Spider-Man es el alter ego de Peter Parker, un joven estudiante y fotógrafo que lucha contra el crimen en Nueva York. Tras ser mordido por una araña radiactiva, desarrolla habilidades sobrehumanas como trepar paredes y lanzar telarañas. Su identidad secreta está motivada por su sentido de responsabilidad y el lema: 'Un gran poder conlleva una gran responsabilidad'."),
            CharacterItem(2, "Iron Man", "https://i.imgur.com/5lDmUOa.jpeg","Iron Man es un superhéroe del universo Marvel, cuyo nombre real es Tony Stark. Es un genio inventor y multimillonario que crea una armadura avanzada para salvar su vida y combatir el mal. Stark utiliza su tecnología y recursos para proteger al mundo, y su identidad como Iron Man es conocida públicamente. Es uno de los miembros fundadores de los Vengadores."),
            CharacterItem(3, "Hulk", "https://i.imgur.com/RxSHhVL.jpeg","Hulk es un superhéroe del universo Marvel, cuyo alter ego es el científico Bruce Banner. Tras exponerse a radiación gamma, Banner se transforma en Hulk, una criatura de gran fuerza física y tamaño descomunal cuando se enfurece. Aunque a menudo lucha por controlar su alter ego, Hulk es un aliado poderoso en la batalla contra amenazas cósmicas y globales, siendo también uno de los miembros originales de los Vengadores."),
            CharacterItem(4, "Wolverine", "https://i.imgur.com/FPeZyaH.jpeg","Wolverine, cuyo nombre real es Logan, es un mutante del universo Marvel conocido por sus habilidades de regeneración, sentidos agudos y garras retráctiles de adamantium, un metal indestructible que recubre su esqueleto. Es miembro de los X-Men y ha vivido por siglos debido a su factor de curación. Con un carácter rudo y solitario, Wolverine lucha con su naturaleza salvaje, pero siempre protege a sus aliados y combate amenazas que ponen en peligro a la humanidad y a los mutantes."),
            CharacterItem(5, "Thor", "https://i.imgur.com/LxL54rn.jpeg","Thor es el dios del trueno en el universo Marvel, basado en la mitología nórdica. Es el hijo de Odín, rey de Asgard, y porta el martillo encantado Mjolnir, que le otorga el poder de controlar el trueno y el rayo. Thor es un guerrero poderoso, conocido por su valentía y lealtad, que defiende tanto a Asgard como a la Tierra de amenazas cósmicas. Es uno de los miembros fundadores de los Vengadores y a menudo lucha para equilibrar su identidad como dios y su conexión con los humanos."),
            CharacterItem(6, "Silver Surfer", "https://i.imgur.com/yfa8gYu.jpeg","Silver Surfer, cuyo nombre real es Norrin Radd, es un personaje del universo Marvel que se convierte en el heraldo de Galactus, el devorador de mundos. Originalmente, Norrin era un habitante del planeta Zenn-La, pero ofreció servir a Galactus para salvar su mundo de la destrucción. A cambio, fue dotado con el 'Poder Cósmico', que le otorga habilidades como viajar a velocidades increíbles por el espacio, manipular energía y tener una fuerza inmensa. Monta una tabla plateada que le permite surfear por el cosmos. A pesar de haber sido un heraldo, Silver Surfer busca redimirse ayudando a proteger el universo."),
            CharacterItem(7, "Capitan America", "https://i.imgur.com/UokjhNP.jpeg","Capitán América, cuyo nombre real es Steve Rogers, es un superhéroe del universo Marvel. Durante la Segunda Guerra Mundial, fue sometido a un experimento que lo convirtió en un súper soldado, dándole fuerza, agilidad y resistencia sobrehumanas. Empuñando un escudo de vibranium, Capitán América lucha por la justicia, la libertad y los valores éticos. Aunque inicialmente quedó congelado en el tiempo, fue rescatado en la era moderna, convirtiéndose en un líder clave de los Vengadores. Es conocido por su carácter noble, su valentía y su firme compromiso con el bien común."),
            CharacterItem(8, "Deadpool", "https://i.imgur.com/5jFnLgY.jpeg","Deadpool, cuyo nombre real es Wade Wilson, es un antihéroe del universo Marvel conocido por su irreverente sentido del humor y su habilidad para romper la cuarta pared, hablando directamente al público. Tras someterse a un experimento que le otorgó un factor de curación acelerado, similar al de Wolverine, Deadpool quedó desfigurado pero casi inmortal. Es un mercenario experto en combate armado y cuerpo a cuerpo, con un enfoque caótico y cómico en sus misiones. Aunque tiene un comportamiento moralmente ambiguo, a menudo se encuentra del lado de los héroes."),
            CharacterItem(9, "Thanos", "https://i.imgur.com/gtxjCJb.jpeg","Thanos es uno de los villanos más poderosos del universo Marvel, conocido por su obsesión con el equilibrio universal. Originario del planeta Titán, Thanos busca recolectar las seis Gemas del Infinito, que juntas le otorgan un poder ilimitado, capaz de manipular la realidad, el tiempo y el espacio. Su objetivo más infame es eliminar la mitad de toda la vida en el universo para evitar lo que él considera una sobrepoblación destructiva. Es un estratega brillante y físicamente formidable, y ha sido uno de los enemigos más grandes de los Vengadores y otros héroes del cosmos."),
            CharacterItem(10, "Scarlet Witch", "https://i.imgur.com/a9DAAXS.jpeg","Scarlet Witch, cuyo nombre real es Wanda Maximoff, es una poderosa heroína del universo Marvel con habilidades de manipulación de la realidad y la magia. Originalmente presentada como una mutante, Wanda tiene el poder de alterar la probabilidad y controlar la energía, lo que la convierte en uno de los seres más poderosos del universo. A lo largo de su historia, ha sido tanto aliada como enemiga de los Vengadores, enfrentándose a su propia lucha interna con el dolor y el control de sus poderes. Su arco más conocido involucra su capacidad para cambiar la realidad, lo que ha generado eventos importantes en el universo Marvel."),
            CharacterItem(11, "Superman", "https://i.imgur.com/79kK4zI.jpeg","Superman, cuyo nombre real es Kal-El, es un superhéroe del universo DC. Originario del planeta Krypton, fue enviado a la Tierra cuando su mundo fue destruido y fue criado como Clark Kent en la Tierra. Bajo el sol amarillo de la Tierra, Superman desarrolló habilidades sobrehumanas, como fuerza extrema, vuelo, velocidad, visión de rayos X, y resistencia casi invulnerable. Conocido como el \"Hombre de Acero\", Superman es un símbolo de justicia, esperanza y bondad, protegiendo la humanidad y enfrentando a enemigos poderosos. Como Clark Kent, también trabaja como periodista en el Daily Planet."),
            CharacterItem(12, "Batman", "https://i.imgur.com/mwSBHqs.jpeg","Batman, cuyo nombre real es Bruce Wayne, es un superhéroe del universo DC. Tras presenciar el asesinato de sus padres cuando era niño, Wayne juró combatir el crimen en Gotham City. Utiliza su inteligencia, habilidades de detective, y una variedad de gadgets y vehículos tecnológicos en lugar de superpoderes. Aunque no tiene poderes sobrenaturales, su entrenamiento físico y mental lo convierte en uno de los combatientes más formidables. Como Batman, busca justicia y protección para Gotham, luchando contra una galería de villanos icónicos mientras mantiene su identidad secreta bajo el disfraz de Bruce Wayne, un millonario filántropo."),
            CharacterItem(13, "Wonder woman", "https://i.imgur.com/6qVHU2I.jpeg","Wonder Woman, cuyo nombre real es Diana Prince, es una superhéroe del universo DC. Originaria de la isla mítica de Themyscira, Diana es una amazona con habilidades sobrehumanas otorgadas por los dioses griegos, como fuerza, velocidad, agilidad y la capacidad de volar. Ella es conocida por su habilidad con la Lazo de la Verdad, sus brazaletes indestructibles, y su escudo y espada. Como princesa de las amazonas, Wonder Woman lucha por la justicia, la igualdad y la paz, defendiendo a la humanidad de amenazas tanto terrenales como sobrenaturales. Su personaje combina una fuerte ética y un profundo sentido del deber con una presencia imponente en el campo de batalla."),
            CharacterItem(14, "Green lantern", "https://i.imgur.com/bdFc07l.jpeg","Green Lantern es un superhéroe del universo DC que usa un anillo de poder para luchar contra el mal. El anillo le permite crear constructos de energía, volar y realizar hazañas extraordinarias, canalizando la fuerza de voluntad del portador. Los Green Lantern Corps son una fuerza policial intergaláctica encargada de mantener la paz en el universo."),
            CharacterItem(15, "Flash", "https://i.imgur.com/svyjHkl.jpeg","Flash es un superhéroe del universo DC conocido por su increíble velocidad. Su identidad más famosa es Barry Allen, un forense que obtiene poderes de velocidad sobrehumana tras un accidente con productos químicos y un rayo. Flash puede moverse a velocidades extremadamente altas, viajar en el tiempo y vibrar a través de objetos sólidos. Es miembro de la Liga de la Justicia y usa su velocidad para luchar contra el crimen y proteger Central City."),
            CharacterItem(16, "Green Arrow", "https://i.imgur.com/40Km6au.jpeg","Green Arrow es un superhéroe del universo DC conocido como Oliver Queen. Es un millonario que se convierte en un vigilante utilizando su habilidad con el arco y las flechas. Después de quedar varado en una isla deshabitada, Queen perfecciona su destreza con el arco y regresa a Star City para combatir el crimen y la corrupción con una variedad de flechas especializadas. Es un miembro de la Liga de la Justicia y lucha por la justicia social y la protección de su ciudad."),
            CharacterItem(17, "Joker", "https://i.imgur.com/3frR7xO.jpeg","El Joker es el archienemigo de Batman en el universo DC. Es un criminal psicópata con un sentido del humor retorcido, conocido por su aspecto de payaso, su piel blanca, cabello verde y sonrisa permanente. Su origen y motivos suelen ser enigmáticos, y es famoso por su caos y anarquía. El Joker no tiene superpoderes, pero es un maestro de la manipulación, el crimen y el terrorismo, y siempre busca desestabilizar a Gotham City y desafiar a Batman."),
            CharacterItem(18, "Lex Luthor", "https://i.imgur.com/fay7sHc.jpeg","Lex Luthor es uno de los principales villanos de Superman en el universo DC. Es un multimillonario y genio criminal conocido por su inteligencia y ambición. Como uno de los hombres más ricos del mundo, Luthor utiliza su fortuna y recursos para diseñar sofisticadas tecnologías y desarrollar planes complejos para derrotar a Superman y alcanzar el poder. Su odio hacia Superman a menudo se basa en la creencia de que el Hombre de Acero es una amenaza para la humanidad."),
            CharacterItem(19, "Darkseid", "https://i.imgur.com/GcgfX0w.jpeg","Darkseid es uno de los villanos más poderosos del universo DC. Es el dictador tiránico del planeta Apokolips y busca conquistar el universo y eliminar el libre albedrío de todos los seres vivos para imponer su voluntad. Posee una fuerza sobrehumana, resistencia y la capacidad de lanzar rayos de Omega, que pueden desintegrar, manipular la materia y alterar la realidad. Su principal objetivo es obtener la Ecuación Anti-Vida, que le permitiría dominar a toda la creación. Darkseid es un adversario formidable para los héroes de la DC, incluyendo a la Liga de la Justicia."),
            CharacterItem(20, "Aquaman", "https://i.imgur.com/VpNywAM.jpeg","Aquaman es un superhéroe del universo DC y el rey de Atlantis. Su nombre real es Arthur Curry, y tiene la capacidad de respirar bajo el agua, comunicarse con la vida marina y posee una fuerza sobrehumana. Equipado con el tridente de Poseidón, Aquaman defiende el océano y la superficie de amenazas, equilibrando su vida entre el mundo submarino y el terrestre. Es un miembro de la Liga de la Justicia y lucha por proteger tanto su reino acuático como la humanidad.")
        )
    }
}
